### ISSUE TITLE
Possible security issue with logout

### ISSUE THREAD

**Issue by myevit** [aws-samples/amazon-cognito-passwordless-auth#126]
Hi, 
I might have found possible security issue.

if you have two tabs open with your website that wrapped with PasswordlessContextProvider / PasswordlessComponent and logout from one tab, the second open tab will be still logged in and site function like user has never logged out. Obviously all cognito api fail. But if there is other sensitive information, it will be still available for third party who want to do some looksy though the site. Page refresh is setting things where they should be.  It will log out also on scheduled token refresh, which can be hours away.

I would assume that apart of the schedule token refresh function that runs infrequent there should be token check function that runs every second and trigger unscheduled token refresh (or page refresh) if tokens are missing.

**Comment by myevit** [comment]
I will get back on this issue after my vacation. The difficulty is that I have dissected your package to a standalone app, rewrote some part of the code to accommodate my application… and for security reasons. 
When I come up with working solution for this issue, I will try to make PR.

**Comment by ottokruse** [comment]
Ok mate, looking fwd to hear more on this. Have a great vacation
