### ISSUE TITLE
`Error: Missing Fido2 config` when not providing `fido2` object to `Config`

### ISSUE THREAD

**Issue by brno32** [aws-samples/amazon-cognito-passwordless-auth#128]
I have the following config

```typescript
Passwordless.configure({
	cognitoIdpEndpoint: `${process.env.USER_POOL_REGION}`,
	userPoolId: `${process.env.USER_POOL_ID}`,
	clientId: `${process.env.USER_POOL_CLIENT_ID}`
})
```

I'm intentionally not passing a `fido2` object because I only want to use the functionality around the Magic Link Sign-In.

However, the above gives me the following error

`Error: Missing Fido2 config`

[Looking at the code](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/9e1641d275bf763592125dd915bd1e060290418f/client/react/hooks.tsx#L699), I can see why. If `fido2` isn't defined, it throws this error.

Am I reading this, right? [The documentation says using fido is optional](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/client/react/README-REACT.md#configuration), but clearly it's required

**Comment by ottokruse** [comment]
Should be optional, so that's a bug. Thanks for the report! If you're interested to send a PR?

**Comment by ottokruse** [comment]
Fix released in https://github.com/aws-samples/amazon-cognito-passwordless-auth/releases/tag/v0.12.1
