### ISSUE TITLE
Question: DefineAuth Fido2 challenge

### ISSUE THREAD

**Issue by smnalex** [aws-samples/amazon-cognito-passwordless-auth#130]
On [25](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/cdk/custom-auth/define-auth-challenge.ts#L25) we issue a challenge if there are no sessions present, but then in the `handleFido2Response` [87](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/cdk/custom-auth/define-auth-challenge.ts#L87) function we expect to have 0 sessions. 
Is there something that I'm missing? Thx!

**Comment by ottokruse** [comment]
You're right, nicely spotted. Lines 87-90 are effectively dead code and should be removed. If you're interested to send a PR?

**Comment by martinpagelaws** [comment]
Changes merged. Closing issue. Thanks!
