### ISSUE TITLE
Value for CDK_STACK_NAME is missing in documentation for End-to-end Example - Back End

### ISSUE THREAD

**Issue by scotthenninger** [aws-samples/amazon-cognito-passwordless-auth#139]
I am following the End-to-end Example - Back End instructions and the value for CDK_STACK_NAME is not defined in the instructions page.  This causes the following error when doing 'npx cdk bootstrap':
    Error("Failed to read CDK_STACK_NAME config from .env file");

Can someone let me know what value to set CDK_STACK_NAME to in .env?

**Comment by scotthenninger** [comment]
Also if I give an arbitrary name I get the following:
   Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment

So are there instructions on how to name the CDK_STACK_NAME tying it to my Amazon account?

**Comment by ottokruse** [comment]
Hi mate, so you're supposed to copy the `.env` file ([this one](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/end-to-end-example/cdk/.env)), which is a template if you will, into `.env.local` and add your own values in there: e-mail address and stack name.

You can choose any stack name you like, it will be used as the CloudFormation stack name, and this unrelated to the way in which CDK determines which AWS account to deploy in.

The way in which CDK determines which AWS account to deploy in is the usual way, that e.g. AWS CLI also uses. Here's exhaustive docs on this: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-authentication.html

I myself usually use a profile like so:

```sh
# Do this once in your shell:
export AWS_PROFILE=myprofile # resolves to an account, you should have set this up before (see link)

# After that you can do:
cdk deploy
```

Note that you can also pass an account ID directly into the source code of the CDK stack, but we don't use that––so the account that is picked will be the one for which you have valid credentials via the process explained above.
