### ISSUE TITLE
authenticateWithSRP() does not work between 4pm and 5pm Pacific Time

### ISSUE THREAD

**Issue by philipbeber** [aws-samples/amazon-cognito-passwordless-auth#145]
Problem: authenticateWithSRP() does not work between 4pm and 5pm Pacific Time. 

Repro steps:

```typescript
import { usePasswordless } from "amazon-cognito-passwordless-auth/react";
...
const { requestSignInLink, authenticateWithSRP } = usePasswordless();
...
      await authenticateWithSRP({
        username: email,
        password,
      }).signedIn;
```
fails with the error
```
TIMESTAMP format should be EEE MMM d HH:mm:ss z yyyy in english.
```
Because the timestamp is formatted incorrectly in the request to AWS:
```
TIMESTAMP: "Sat Feb 17 24:03:00 UTC 2024"
```
It should be:
```
TIMESTAMP: "Sat Feb 17 00:03:00 UTC 2024"
```

**Comment by ottokruse** [comment]
Wow nice find!

I'm a bit baffled, how could this time format ever return 24 😱 That's weird no ? No clock in the world (that I know of) shows 24 instead of 0 for hour. Wonder if this is a browser bug. Can't quickly find any specific wording on this issue in the ECMAscript specs but I'll keep digging a bit.

**Comment by ottokruse** [comment]
Firefox and Safari both show "00", but Chrome shows "24" for:

```js
new Intl.DateTimeFormat("en-US", {
    hour: "2-digit",
    timeZone: "UTC",
    hour12: false,
  }).formatToParts(new Date("2000-01-01T00:00:00.000Z")).find((part) => part.type === "hour").value
```

**Comment by ottokruse** [comment]
Ofc we're not the first lib to bump into this: https://github.com/home-assistant/frontend/pull/11426

**Comment by ottokruse** [comment]
Fixed in https://github.com/aws-samples/amazon-cognito-passwordless-auth/releases/tag/v0.12.2
