### ISSUE TITLE
Amplify cli end-to-end example

### ISSUE THREAD

**Issue by juanf9224** [aws-samples/amazon-cognito-passwordless-auth#163]
Hi, Thanks for bringing this gem to the world!

I tried to replicate the steps on the end to end example but with amplify but no luck (I'll keep trying!) but it would be great if there could be an end to end example using amplify cli.

first error was due to not having esbuild as a dependency and then after installing it got another error but this time from the esbuild execution.

So if this is something that will happen, I would truly appreciate it!.

**Comment by ottokruse** [comment]
Thanks for registering the interest!

Please update here should you get it working (I think it should but we haven't explicitly tested with Amplify CLI so I'm also not surprised there's gotchas)

**Comment by juanf9224** [comment]
@ottokruse For sure!

One config that I'm having issues with is the user pool, in the [basic usage](https://github.com/aws-samples/amazon-cognito-passwordless-auth?tab=readme-ov-file#basic-usage) example it says we can pass an existing user pool but I don't see an example on how to pass it, is there one or how can I pass an existing user pool since using `.fromUserPoolId` is not an option

**Comment by ottokruse** [comment]
Hi mate. That allows you to pass in a User Pool that you create in the same CDK stack, but not a User Pool that is external to the CDK stack (an IUserPool). That is not supported (yet) unfortunately, here's more info and the work around: https://github.com/aws-samples/amazon-cognito-passwordless-auth/issues/118#issuecomment-1983697750

**Comment by ottokruse** [comment]
If you share the CDK code you use I can be more specific to your case.

**Comment by juanf9224** [comment]
Thanks! that was actually what we were looking at doing if it wasn't possible to use the existing one in the same cdk, about the used cdk, no worries, I was using the example one and testing, wanted to confirm this! 🚀
