### ISSUE TITLE
Dependency issue while implementing this tutorial

### ISSUE THREAD

**Issue by ThisisBada** [aws-samples/amazon-cognito-passwordless-auth#167]
Hello Team,

I've been trying to implement this tutorial I followed all the steps but I had an issue in the Create Your Front end > Add passwordless authentication while executing this command : 
npm install amazon-cognito-passwordless-auth 

Error : 

npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: webapp@0.0.0
npm error Found: react@18.3.1
npm error node_modules/react
npm error   peer react@"^18.3.1" from react-dom@18.3.1
npm error   node_modules/react-dom
npm error     react-dom@"^18.2.0" from the root project
npm error   react@"^18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error amazon-cognito-passwordless-auth@"*" from the root project
npm error
npm error Conflicting peer dependency: react@18.2.0
npm error node_modules/react
npm error   peer react@"18.2.0" from react-native@0.74.1
npm error   node_modules/react-native
npm error     peer react-native@"*" from react-native-passkey@2.1.1
npm error     node_modules/react-native-passkey
npm error       peer react-native-passkey@">=1.1.1" from amazon-cognito-passwordless-auth@0.13.2
npm error       node_modules/amazon-cognito-passwordless-auth
npm error         amazon-cognito-passwordless-auth@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/ec2-user/.npm/_logs/2024-05-10T13_41_04_015Z-eresolve-report.txt

npm error A complete log of this run can be found in: /home/ec2-user/.npm/_logs/2024-05-10T13_41_04_015Z-debug-0.log

This seems like a dependency issue between react and the amazon-cognito-passwordless-auth  package.

Please review and fix this as it public tutorial of AWS.

Tutorial Link : https://catalog.workshops.aws/cognito-webauthn-passwordless/en-US/30-frontend/32-add-passwordless

**Comment by ottokruse** [comment]
Thanks for reporting. Will have to look into it. 

To work around for now, use the --force flag for the npm install.

**Comment by ThisisBada** [comment]
Hello,

Thanks for your answer.

the --force flag will not generate errors but also will NOT remove the error for amazon-cognito-passwordless-auth package in the react code.

**Comment by alejandrog79** [comment]
Hi! I resolved this particular issue installing this dependencies at once:

`npm install react@18.2.0 react-dom@18.2.0 amazon-cognito-passwordless-auth`

**Comment by ottokruse** [comment]
Should be fixed in version #182
