### ISSUE TITLE
FrontEnd Shows "Unexpected End of JSON Input"

### ISSUE THREAD

**Issue by kfayal-iotecha** [aws-samples/amazon-cognito-passwordless-auth#168]
After deploying the back end and adding a user in cognito, I started the front end with npm run dev, then accessed the front end via the URL link http://localhost:5173/.  I then entered the email address of the user I added in Cognito and clicked Next.  Next the following screen appeared with the text "Unexpected End of JSON Input" at the bottom of the screen.

![image](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/128632688/0cd36fd0-611b-4a7b-9416-e2d3d444c852)

**Comment by ottokruse** [comment]
Hi mate. Thanks for reporting.

Have a look in the network tab of your browser and see what data is actually coming back? My guess is it's not JSON but some error HTML or so. Probably the root cause is in there.

**Comment by kfayal-iotecha** [comment]
Ah yes, it is showing that there is an attempt to connect to:
http://localhost:5173/changeme/sign-in-challenge, and it's getting a 404 error. 

I have set up the .env-local with the outputs of the backend CDK.  It seems like that "changeme" in the url is supposed to be replaced with something?

**Comment by kfayal-iotecha** [comment]
Steps to duplicate:
1. In Windows WSL2 (Ubuntu) clone project to /projects folder
2. NPM install and deploy backend CDK according to instructions in Backend CDK readme  Successful
3. Create user account in Cognito user pool created by deployment of backend
4. NPM install and npm run dev frontend. Go to http://localhost:5173 to get login page.
5. Enter users email and click Next

**Comment by ottokruse** [comment]
Can you double check the name of your .env.local file? (Note the dots, you have a dash in the name but maybe I see in your comment but that's not right)

**Comment by kfayal-iotecha** [comment]
Oh boy.. nice to have another set of eyes.  Eiii.. Yes, that .env.local was the cause of the issue for "Unexpected end of JSON input"!  So it runs locally now.

I am still trying to deploy the SPA to S3 using the deploy-spa.cjs script, but I'm still getting the same error. "Error: Region is missing"  I realize this is two topics under the same issue.. Should I open another issue?

**Comment by kfayal-iotecha** [comment]
I'm going to close this issue because I can get it to work on my Mac, but not in WIndows for some reason.

**Comment by kfayal-iotecha** [comment]
I was easily able to get this to work on my Mac, but had problems with getting it to work in my Ubuntu WSL2 environment.  So closing it.
