### ISSUE TITLE
Can we load logo from assets folder locally

### ISSUE THREAD

**Issue by cordev-developer** [aws-samples/amazon-cognito-passwordless-auth#183]
Hi guys,

Hope you are doing well. Lastly I've been working with the React Example with FIDO2, especifically I have one doubt about why we need to load the logo from our brand with a URL, I wonder if maybe is there a possibility to load our brand logo from local folder in Visual Studio Code. I refer to this part of code in which we see the logo URL, maybe is it possible ?:

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <PasswordlessContextProvider enableLocalUserCache={true}>
    <PasswordlessComponent
      brand={{
        backgroundImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Manhattan_in_the_distance_%28Unsplash%29.jpg/2880px-Manhattan_in_the_distance_%28Unsplash%29.jpg",
        customerName: "Amazon Web Services",
        customerLogoUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png",
      }}
    >
      <React.StrictMode>
        <App />
      </React.StrictMode>
    </PasswordlessComponent>
    <Fido2Toast /> {/* Add Fido2Toast below App so it is rendered on top */}
  </PasswordlessContextProvider>
);

**Comment by ottokruse** [comment]
Hi mate. Not sure would have to experiment. Wouldn't be surprised if this would just work:

```js
import backgroundImageUrl from "./path1/backgroundImageUrl.png";
import customerLogoUrl from "./path2/logo.png";

<PasswordlessComponent brand={{backgroundImageUrl, customerName: "Your company", customerLogoUrl}}>
```



Suggest to check out Vite docs: https://vitejs.dev/guide/assets

**Comment by ottokruse** [comment]
Hi mate. Sure feel free to email me (you can find my email in my commits ;))
However if you have non-sensitive questions that would help others as well to know the answer to, please just use a GitHub issue (best: a new issue for each question).

GREAT WORK you're doing, thank you for spreading Cognito knowledge!

**Comment by cordev-developer** [comment]
Hi ottokruse, ok great ! I will follow your recommendations, I thought it's a great idea to share the questions with other mates. I will continue with my new section about Passkeys and FIDO2, thanks a lot !

Have an awesome day ahead.
