### ISSUE TITLE
[Need Help] Using this library with Next.js server components

### ISSUE THREAD

**Issue by kitadakyou** [aws-samples/amazon-cognito-passwordless-auth#190]
Hi

I want to integrate this library into a project that uses Next.js Server Components (which is recommended to use the latest Next.js).

Based on the documentation, it appears that the library relies on React Context, which restricts its use to Next.js Client Components at top level.

Functions like `signUp()` are exported from the `cognito-api`, but attempting to call them results in an error.

Upon reviewing the code, I noticed that [these functions internally call the configure() function without any arguments.](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/client/cognito-api.ts#L460) It requires React Context.

This is same for other exported functions as well.

```
async function signUp({ /* args */ }) {
  const { fetch, cognitoIdpEndpoint, proxyApiHeaders, clientId, clientSecret } = configure();
  // signup codes
}
```

The code snippet provided in the "Usage in (plain) Web" section results in an error without `use client` directive.

```
Passwordless.configure({
  // some configuration
})
```

The only workaround I could think of was [to call configure() without arguments and have it read the values from environment variables.](https://github.com/kaibutsu50/amazon-cognito-passwordless-auth-without-context/commit/70852d39ca9ee7bd6bd3aabd5d575efa1cb02a67#diff-2f48b6bfe037e86dceefddad2c104408491b835a48406ee29804fd1bfc45ca19)

```
export function configure(config?: Config) {
  if (config) {
    const config_: ConfigWithDefaults = {
      ...config,
      crypto: config.crypto ?? Defaults.crypto,
      storage: config.storage ?? Defaults.storage,
      fetch: config.fetch ?? Defaults.fetch,
      location: config.location ?? Defaults.location,
      history: config.history ?? Defaults.history,
    };
    config_.debug?.("Configuration loaded:", config);
    return config_;
  } else {
    const myConfig: Config = {
      userPoolId: process.env.COGNITO_USER_POOL_ID ?? '',
      clientId: process.env.COGNITO_USER_POOL_CLIENT_ID ?? '',
      cognitoIdpEndpoint: process.env.AWS_REGION ?? '',
      fido2: {
        baseUrl: process.env.FIDO2_API_URL ?? '',
        authenticatorSelection: {
          userVerification: 'required'
        }
      },
    }
    return {
      ...myConfig,
      crypto: myConfig.crypto ?? Defaults.crypto,
      storage: myConfig.storage ?? Defaults.storage,
      fetch: myConfig.fetch ?? Defaults.fetch,
      location: myConfig.location ?? Defaults.location,
      history: myConfig.history ?? Defaults.history,
    };
  }
}
```

Is there a better solution to this problem?

**Comment by ottokruse** [comment]
Yes the react components require context and are thus limited to use_client. 

The non react specific code (such as cognito-api) should work regardless, but require you to call configure with a configuration object first, ie in the entry point of your app. 

Then if you're not on web, you'll have to provide implementations for "special" attributes such as crypto that do not exist across all JS runtimes.

**Comment by ottokruse** [comment]
Have a read of this to understand how it's supposed to work: https://github.com/aws-samples/amazon-cognito-passwordless-auth/pull/87

**Comment by kitadakyou** [comment]
Hi! [ottokruse](https://github.com/ottokruse)

Thank you very much! That worked perfectly.

I apologize for missing the reference to Issue #87 earlier.
