### ISSUE TITLE
"internal server error" whn clicking signin with magic link

### ISSUE THREAD

**Issue by deanbushmiller** [aws-samples/amazon-cognito-passwordless-auth#193]
I watched your video, set it up twice from backend / client instructions
My ses is still in sandbox mode but I have sent a successful email test to self
I am using mac/safari to build and run 
No errors on build of back and front end.
-If you can point me to troubleshooting / logs I am happy to look but I am stumped right now.
One other thing- I have the email domain in another account * but the test did work

**Comment by ottokruse** [comment]
Check Cloudwatch Logs, there should be a full error message there.

Check the log groups for all the lambda functions that were deployed with this solution. 

Most common issue is having wrong values in the env.local files so best double check them.

**Comment by ottokruse** [comment]
Otherwise please leave a detailed description of how you deployed and which steps you take that lead you to the error, so we can attempt to reproduce.
