### ISSUE TITLE
Bug: SMS OTP sent to unverified phone

### ISSUE THREAD

**Issue by mdesousa** [aws-samples/amazon-cognito-passwordless-auth#199]
hi, noticed this bug in `sms-otp-stepup.ts`

in the lines below:

```
  let phoneNumber = event.request.userAttributes.phone_number_verified
    ? event.request.userAttributes.phone_number
    : undefined;
```

`phoneNumber` is populated if `phone_number_verified` is `"false"` (which is a string and is truthy)

**Comment by ottokruse** [comment]
TIL Just confirmed it.

Thanks for the report. Are you interested in sending a PR for it?

**Comment by ottokruse** [comment]
(Sidenote: in the JWT ID token the field __is__ boolean, not string. But in the Cognito triggers, it is string, so `"true"` or `"false"`.)

**Comment by mdesousa** [comment]
hi @ottokruse submitted PR #201

**Comment by ottokruse** [comment]
Thanks for the PR. We'll close the issue once we have published a new version to npm
