### ISSUE TITLE
Suppress 'Incorrect username or password' message when requesting a magic link for a non-existent user.

### ISSUE THREAD

**Issue by mcdermc** [aws-samples/amazon-cognito-passwordless-auth#213]
Hi,

I am using amazon-cognito-passwordless-auth version 0.14.3
I deployed the end-to-end-example/cdk and end-to-end-example/client. 
I made no changes to the code before or after deployment.

After deployment, I enabled the 'Prevent user existence errors' option for the Cognito app client of the Userpool. 
![image](https://github.com/user-attachments/assets/8d2df362-9eda-46b7-8aef-acc799fc6863)

I added a user to the Cognito Userpool, requested a Magic Link, received the link and the link signed me into the website, as expected. All good.

I then tried signing in with the email of a **_user that does not exist_** in the Userpool.

I entered the email address and clicked the 'Next' button:
![image](https://github.com/user-attachments/assets/7a800776-8603-4716-9817-69a3ac418035)

I then clicked the 'Sign in with magic link' button:
![image](https://github.com/user-attachments/assets/d3a9e348-6cf6-4392-ad3a-8af38fc54295)

I saw the 'Starting sign-in' message:
![image](https://github.com/user-attachments/assets/ad1ff26a-5832-4f1f-87dd-92512fd6320a)

Then I saw the following error - 'Incorrect username or password':
![image](https://github.com/user-attachments/assets/d6b0d415-ac39-4b99-876a-3b30b45532de)

Because I had enabled the 'Prevent user existence errors' on the Userpool app client, what I expected to see was a message saying an email was sent (to the non-existent email address), so that user enumeration was not possible.  

This expected behavior has been described here: https://github.com/aws-samples/amazon-cognito-passwordless-auth/issues/200#issuecomment-2404245689

The expected behavior is described in the linked comment as - "If a non-existent user requests a magic link (and you have enabled prevent user existence errors) then it will look to the user that the email will be sent, but it actually doesn't happen --> thus preventing user enumeration".

I realize the comment above is from an issue that was closed a little while ago, so I am wondering if there were any code changes in the interim that may have changed this behavior?

**Comment by ottokruse** [comment]
Can reproduce. Not sure why this happens! This should work. I can see that the defineAuth trigger nicely returns:

```
{
  "challengeName": "CUSTOM_CHALLENGE",
  "issueTokens": false,
  "failAuthentication": false
}
```

But still Cognito returns the "Incorrect username or password" error.

**Comment by ottokruse** [comment]
Found it, see #214

**Comment by mcdermc** [comment]
Excellent!  Thanks @ottokruse.

**Comment by ottokruse** [comment]
Released: https://github.com/aws-samples/amazon-cognito-passwordless-auth/releases/tag/v0.14.4
