### ISSUE TITLE
Usage in a Vite/Vue App

### ISSUE THREAD

**Issue by christ-offer** [aws-samples/amazon-cognito-passwordless-auth#22]
Hey, I am currently trying to implement the magic link login in a Vite/Vue app.

As soon as I install the npm package I get the following error trying to run it in dev mode (before adding any other code):

![image](https://user-images.githubusercontent.com/5350223/236808817-2082845d-6add-406a-b451-b841c4eadc61.png)

The thing is, all of those react packages are already in the node_modules folder before adding it.

I have tried to add react, react-dom, etc to the "external" build option and ssr option. But no improvements.

Any idea what I am doing wrong? Is it simply not possible to use this in a Vite/Vue app?

**Comment by christ-offer** [comment]
I cant share much code from the project as its not public, but I dont even have to add any code for the error to arise. Its a vue3 app running on vite with a pinia(ts) store for auth.

As soon as I npm -i amazon-cognito-passwordless-auth it stops working with the error I posted above.

Im on node 16.16, I dont know if that matters? 

Here is a fuller error:

![image](https://user-images.githubusercontent.com/5350223/236847597-933b5437-983e-4e65-8dcc-de26407559c1.png)

I have tried adding anything react into build.rollupoptions.external and ssr.external, but no change.

**Comment by ottokruse** [comment]
Mmmm. This is little to work with for us but it looks like it's an interplay issue with something else. Did you expect to see react-redux in your dependency tree? Since you mentioned Vue and pinia.
The lib here is not installing react-redux.
The error you see is from esbuild not rollup, so you may need to tweak esbuild config via vite options.
When do you see the error. From your screen shots it is not even clear this is an issue with the lib here.

**Comment by christ-offer** [comment]
Hey there! Feel free to close it (Ill leave it up to you). The temporary solution of adding react-dom and excluding it from all builds is working fine atm. 
Tho the error only appears after adding this library. So I dont really know whats going on to be fair. Haha.

**Comment by ottokruse** [comment]
Ok sure. Will close for now as I don't see leads to pursue currently. Should they arise we'll re-open
