### ISSUE TITLE
Combined lambda functions?

### ISSUE THREAD

**Issue by paulf69487623** [aws-samples/amazon-cognito-passwordless-auth#28]
Hello,

This isn't really an issue per se, but I don't see a discussion section on this repository.

I've been working on a very similar project since last fall, which hasn't been published yet.  I started with separate lambda functions for challenge define/create/verify, but I later combined them into a single lambda.  For a low-traffic site, or one that doesn't re-authenticate very often, a user could experience 3 cold-starts for the lambda functions - one for each.  I've especially noticed that the first DynamoDB connection can take some time on a cold start.  By using a single lambda, you only experience these delays once.  This is a little less conceptually clear, but it could provide a better user experience.

The event that gets delivered to the function specifies what triggered the event.  This is the relevant section from my code:

```
        switch (event.triggerSource) {
            case 'DefineAuthChallenge_Authentication':
                return define_handler(event, context, callback);
            case 'CreateAuthChallenge_Authentication':
                return create_handler(event, context, callback);
            case 'VerifyAuthChallengeResponse_Authentication':
                return verify_handler(event, context, callback);
            default:
                console.log("In the default case - no trigger source");
                return "No trigger source - not sure what to do";
```

With a combined function, you just attach the same function to each trigger on the user pool:

```
      upool.addTrigger(
        UserPoolOperation.DEFINE_AUTH_CHALLENGE,
        this.challengeHandler
      );

      upool.addTrigger(
        UserPoolOperation.CREATE_AUTH_CHALLENGE,
        this.challengeHandler
      );

      upool.addTrigger(
        UserPoolOperation.VERIFY_AUTH_CHALLENGE_RESPONSE,
        this.challengeHandler
      );
```

Thoughts?

Thanks,

Pau

**Comment by ottokruse** [comment]
I don't see any fundamental problem with that. Interesting idea to limit cold starts that way for low traffic sites.
