### ISSUE TITLE
userPoolClients not being created

### ISSUE THREAD

**Issue by pchaganti** [aws-samples/amazon-cognito-passwordless-auth#3]
All resources are being created as shown in the doc when using the sample code. Except for a **userPoolClient**. Not passing any existing userpool or client, so the stack should be creating the userPoolClients after creating the userpool.

Anyone know why it is not being created? 

thanks!

**Comment by pchaganti** [comment]
UserPoolClients are only added if fido2 is being used. I am not using fido2 so that explains why no clients were added by the stack.

Is a userPoolClient NOT needed for a magic link?


thanks!

**Comment by ottokruse** [comment]
Also needed but if you don't deploy FIDO2 we don't have to know about the clientId for the FIDO2 api, so we opt to not create the client ourselves and let the dev (you) do it yourself. We try to create as little as we can. But might be confusing in this case!

Thanks for your interest in this solution.

**Comment by pchaganti** [comment]
Got it. 

thanks!
