### ISSUE TITLE
Link from old repository

### ISSUE THREAD

**Issue by atsushi-ishibashi** [aws-samples/amazon-cognito-passwordless-auth#55]
Until recently, I wasn't aware of this project so was referring to the below old repository.
https://github.com/aws-samples/amazon-cognito-passwordless-email-auth

Unfortunately the old one was archived so I have no idea how to do it.
But there may be a lot of people who refers to the old like me, it would better to do something resolving the problem.

**Comment by ottokruse** [comment]
Good point, working on it, need to get the old repo unarchived to be able to add a banner to it

**Comment by ottokruse** [comment]
Done!
