### ISSUE TITLE
Documentation:  Security Posture

### ISSUE THREAD

**Issue by Simonl9l** [aws-samples/amazon-cognito-passwordless-auth#68]
Per the [FAQ](https://github.com/aws-samples/amazon-cognito-passwordless-auth#how-have-you-tested-the-security-posture-of-this-solution) on Security Posture.

Per the advice - in the thought that this is a reference implementation:

> Having said that, you should know that this solution was written by Amazon Cognito experts from AWS. We have run it through multiple internal reviews. We've used it for several of our projects. Amazon's application security team has reviewed and pentested it.

If would be great if such review findings, and pertinient details of pen-testing results were shared with applicable remediations tied to commits over time.

Whist we don't plan to use this solution as it stands but porting it to dotnet, inserting an overall API layer (via Lambda Minimal API)  and leveraging [fido2-net-lib](https://github.com/passwordless-lib/fido2-net-lib) to tie to our use case, it's good to track any changes here as a reference such that we can also make corresponding changes here.

We also note there in some paces scattered across the code there are mentions of security implications. An [example](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/6e1bfa8e28cd2145d0f5c3d3b0ecd3a3f3573123/cdk/lib/cognito-passwordless.ts#L68) of this is:
```TS

...
 /**
         * Should users who previously registered FIDO2 credentials be forced to sign in with FIDO2?
         * FIDO2 is a phishing resistant signInMethod. As long as other signInMethods are still available,
         * there is a risk of phishing to the user, e.g. an attacker might trick the user into revealing the magic link.
         * Set to `true` to disallow other custom signInMethods if the user has one or more FIDO2 credentials.
         * @default false
         */
enforceFido2IfAvailable?: boolean;
       

...
```

It would be good to collect such comments in one place?

At the end of the day its surely valuable that AWS customers can leverage the value-add of this information, whilst of cause performing their own due diligence.

**Comment by ottokruse** [comment]
Thank you for your interest in this solution.

> If would be great if such review findings, and pertinient details of pen-testing results were shared with applicable remediations tied to commits over time.

At this point there are no such findings, all were resolved during internal design, development and pen-testing, prior to public release. Changes made after public release were all "tweaks" to make things nicer––i.e. no fixes for security issues.

We maintain [Releases](https://github.com/aws-samples/amazon-cognito-passwordless-auth/releases) in GitHub and it would be good for you to keep on eye on these release notes. We will make sure to document there any changes with security implications (in a lightweight way). Thank you for making sure we're aware of your needs, that are most likely shared by other customers too.

> We also note there in some paces scattered across the code there are mentions of security implications. An example of this is: ...
> It would be good to collect such comments in one place?

That comment is in the public interface of the main CDK class which seems like a good place. This is what developers see, if they use the package. We might also put this remark in the docs (e.g. README), that would surely make sense as well.

It would be helpful if you can point to more examples like that, that you'd expect to be more visible on the surface?

**Comment by ottokruse** [comment]
Closing for now
