### ISSUE TITLE
Documentation: End-toEnd Example - SMS Setup & config for Step Up Auth

### ISSUE THREAD

**Issue by Simonl9l** [aws-samples/amazon-cognito-passwordless-auth#72]
We were under the impression that one can setup SMS as the OTP, it's not clear how this is achieved via the sample UX. 

Also In trying to use the "Step Up Auth":
 
![Screenshot 2023-08-06 at 3 51 56 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/66816457/5687e216-7bc8-4a62-946a-5aef7f013955)

It seem that needs to be more configured in SNS to enable this to work? 

Additional documentation would be helpful here!

Thanks!

**Comment by ottokruse** [comment]
This is for step up auth (where you are already signed in and prove that it is still you by providing the OTP that is sent by SMS).

**Comment by ottokruse** [comment]
You have read this I take it? ./SMS-OTP-STEPUP.md

What is unclear? I'm agreeing that our docs are pretty sparse 😓 but we won't get to full coverage overnight so would love to hear what's unclear specifically in this case. 

Thanks !

**Comment by ottokruse** [comment]
It uses SNS. And if you're in the USA (and some other countries) you have to configure the right settings for SNS , such as sender ID. You can pass these through to Passwordless CDK construct contatructor parameters

**Comment by ottokruse** [comment]
See if SNS publishing works for you with AWS CLI:

```shell
aws sns publish \
    --phone-number "+1234567890" \
    --message "Your message here" \
    --message-attributes '{
        "AWS.SNS.SMS.SMSType": {
            "DataType": "String", 
            "StringValue": "Transactional"
        },
        "AWS.SNS.SMS.SenderID": {
            "DataType": "String", 
            "StringValue": "YourSenderID"
        },
        "AWS.MM.SMS.OriginationNumber": {
            "DataType": "String", 
            "StringValue": "+0987654321"
        }
    }'
```

You might still be in the SNS sandbox, which could be why it's not working for you: https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox.html

**Comment by ottokruse** [comment]
I don't understand why AWS CLI would work but not from our code.

Saw you explicitly passing the snsRegion in the CDK code. That because it's different from the stack region?

Are you indeed out of the SNS sandbox?

**Comment by ottokruse** [comment]
You only need to provide `snsRegion` if different from the region -- the intent is to be able to use another region where you might be out of the SNS sandbox (sandbox being per region).
We should add this to the inline docs.

> If the CLI call works that would indicate out of the sandbox ?
Don't think so, but it is surprising to me that CLI works but not from the Lambda function.
But if you're not sure if you're in the SNS sandbox then you probably are still in it and that can lead to messages being lost in space without error.
Check the Create Auth lambda logs too? Any hints in there about the SMS not being sent?

**Comment by ottokruse** [comment]
Any luck?
Sanity check: The user does exist right? Because with the user pool client setting of `preventUserExistenceErrors` of `true` the system will not show an error if the user doesn't exist: it will appear to proceed, but the SMS won't actually be sent then.

**Comment by ottokruse** [comment]
Closing for now, let us know if there's still an issue, will re-open then
