### ISSUE TITLE
install-passwordless-local npm run task does not seem to work

### ISSUE THREAD

**Issue by Simonl9l** [aws-samples/amazon-cognito-passwordless-auth#85]
Per the end-to-end-example, if one runs the `install-passwordless-local` in the hope that it will use the local implementation of the passswordles JSX components. Subsequently if one tries to run the example locally per `rpm run dev`, this error is displayed:
```
[plugin:vite:import-analysis] Failed to resolve entry for package "amazon-cognito-passwordless-auth". The package may have incorrect main/module/exports specified in its package.json.
```
is there a documented procedure to get this to work?

**Comment by ottokruse** [comment]
Hi @Simonl9l That's an internal script for dev usage and the way it works is, you edit the library as you see fit and then run `npm run dist` in the repo root. After that, you can do `npm run  install-passwordless-local` and you get the local one instead of the one on npm.

**Comment by ottokruse** [comment]
Closing for now, let us know if there's still an issue
