### ISSUE TITLE
End-to-end-example CDK deployment fails due to error

### ISSUE THREAD

**Issue by lrivera-identivize** [aws-samples/amazon-cognito-passwordless-auth#91]
When I run `npx cdk deploy`, the deployment fails with the following error:
~~~
4:41:21 PM | CREATE_FAILED        | AWS::ApiGatewayV2::Stage                        | PLHttpApiPLDefaultStage9CEDBFC2
Cannot enable logging. Policy document length breaking Cloudwatch Logs Constraints, either < 1 or > 5120 (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: Ba
dRequestException; Request ID: 3194b994-036d-4c86-b86f-efe54758e130; Proxy: null)
~~~
CDK Version: 2.96.2 (build 3edd240)

I've made various changes to the input variables available to me to see if they are contributing to hitting the size constraints. And the error persists.

**Comment by lrivera-identivize** [comment]
Update: Added packaged installation (npm install) to my prototype project, setup project according to documentation, and the error showed up in the initial deployment.

**Comment by ottokruse** [comment]
Thanks for your interest in this solution. 

What exact versions of the CDK packages are you using?

**Comment by ottokruse** [comment]
Thanks ! Will have a look

So deploying fails consistently? And does updating CDK help?

**Comment by lrivera-identivize** [comment]
It fails consistently. I had the latest version of CDK and related packages installed when I noticed the error. I refactored the packaged version to `aws-cdk-lib@2.83.1` as I posted in an attempt to troubleshoot the issue.

**Comment by ottokruse** [comment]
Maybe this is your issue?: https://stackoverflow.com/a/73809372/1376848

Do you have a lot of APIs in this account with access logging enabled?

**Comment by lrivera-identivize** [comment]
Yep, that was it! 

I was beginning to wonder if this might have something to do with our AWS account. 

Thanks for the time and effort...and the save.

Cheers!

**Comment by ottokruse** [comment]
Great! 🎉
